name: Build and Deploy

on:
  push:
    branches:
      - master  # 트리거 브랜치

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 필요한 Node.js 버전

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Build
      run: npm run build  # 프로젝트 빌드

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # 배포할 브랜치
        folder: build  # 빌드된 파일이 있는 디렉토리
        token: ${{ secrets.GITHUB_TOKEN }}
